import os
import re

APP_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'app', 'lib'))
OUT_FILE = os.path.join(APP_DIR, 'ui', 'components', 'tr_strings.dart')

def extract_strings():
    all_strings = set()
    # Matches tr('something')
    pattern = re.compile(r"tr\('([^']+)'\)")
    
    for root, _, files in os.walk(APP_DIR):
        for file in files:
            if not file.endswith('.dart'):
                continue
            with open(os.path.join(root, file), 'r', encoding='utf-8') as f:
                content = f.read()
                matches = pattern.findall(content)
                all_strings.update(matches)
    
    sorted_strings = sorted(list(all_strings))
    print(f"Extraction complete: {len(sorted_strings)} unique strings found.")
    
    dart_code = "/// AUTOGENERATED FILE - DO NOT EDIT MANUALLY\n"
    dart_code += "/// This file contains all the unique strings wrapped in tr('...') across the app.\n"
    dart_code += "/// It is used to preload translations on language change to ensure synchronous tr() works.\n\n"
    dart_code += "const List<String> allAppStrings = [\n"
    
    for s in sorted_strings:
        # Escape any single quotes just in case, though they shouldn't be inside a single-quote regex group natively
        escaped = s.replace("'", "\\'")
        dart_code += f"  '{escaped}',\n"
        
    dart_code += "];\n"
    
    with open(OUT_FILE, 'w', encoding='utf-8') as f:
        f.write(dart_code)
    print(f"Wrote strings to {OUT_FILE}")

if __name__ == '__main__':
    extract_strings()
